// src/api/marketplaces/marketplace.js
// Capa de "backend fake" para Marketplace B2C y B2B

// ------------------------------------------------------
// B2C: productos orientados a paciente / consumo
// ------------------------------------------------------
const B2C_PRODUCTS = [
  {
    id: 1,
    name: "Losartán 50mg - Antihipertensivo",
    category: "medications",
    provider: "Farmacia Central",
    price: 25.5,
    priceVES: 918.0,
    discount: 15,
    stock: 45,
    rating: 4.8,
    deliveryTime: "2-3 días",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    insuranceCompatible: true,
    isNew: false,
    availableFor: ["b2c", "b2b"],
    description:
      "Medicamento antihipertensivo para el control de la presión arterial alta",
    prescription: true,
    genericAlternative: "Losartán Genérico",
    sideEffects: "Mareos, dolor de cabeza leve",
    dosage: "Una tableta diaria",
  },
  {
    id: 2,
    name: "Tensiómetro Digital Automático",
    category: "medical-equipment",
    provider: "MediSupply VE",
    price: 89.99,
    priceVES: 3239.64,
    discount: 0,
    stock: 12,
    rating: 4.6,
    deliveryTime: "1-2 días",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    insuranceCompatible: false,
    isNew: true,
    availableFor: ["b2c"],
    description: "Monitor de presión arterial digital con pantalla LCD grande",
    prescription: false,
    warranty: "2 años de garantía",
    features: "Memoria para 90 mediciones, detección de arritmia",
  },
  {
    id: 3,
    name: "Paracetamol 500mg (100 tabletas)",
    category: "medications",
    provider: "Farmacia Central",
    price: 12.75,
    priceVES: 459.0,
    discount: 0,
    stock: 156,
    rating: 4.6,
    deliveryTime: "1-2 días",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    insuranceCompatible: true,
    isNew: false,
    availableFor: ["b2c", "b2b"],
    description: "Analgésico y antipirético para dolor y fiebre",
    prescription: false,
    dosage: "1-2 tabletas cada 6-8 horas",
    maxDaily: "Máximo 8 tabletas diarias",
  },
  {
    id: 4,
    name: "Vitamina D3 2000 UI (60 cápsulas)",
    category: "wellness",
    provider: "Wellness Store",
    price: 18.5,
    priceVES: 666.0,
    discount: 0,
    stock: 89,
    rating: 4.4,
    deliveryTime: "2-3 días",
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    insuranceCompatible: false,
    isNew: false,
    availableFor: ["b2c"],
    description:
      "Suplemento de vitamina D3 para fortalecer el sistema inmune y la salud ósea",
    prescription: false,
    dosage: "1 cápsula diaria con alimentos",
    benefits: "Fortalece huesos y sistema inmune",
  },
  {
    id: 5,
    name: "Glucómetro con 50 Tiras Reactivas",
    category: "diagnostics",
    provider: "Laboratorio Nacional",
    price: 45.75,
    priceVES: 1647.0,
    discount: 10,
    stock: 28,
    rating: 4.7,
    deliveryTime: "2-4 días",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    insuranceCompatible: true,
    isNew: false,
    availableFor: ["b2c", "b2b"],
    description: "Medidor de glucosa en sangre con tiras reactivas incluidas",
    prescription: false,
    warranty: "5 años de garantía",
    includes: "Lancetas, estuche de transporte",
  },
  {
    id: 6,
    name: "Termómetro Infrarrojo Sin Contacto",
    category: "medical-equipment",
    provider: "MediSupply VE",
    price: 32.99,
    priceVES: 1187.64,
    discount: 0,
    stock: 67,
    rating: 4.5,
    deliveryTime: "1-2 días",
    image: "https://images.unsplash.com/photo-1584432810601-6c7f27d2362b?w=400",
    insuranceCompatible: false,
    isNew: true,
    availableFor: ["b2c"],
    description:
      "Termómetro digital infrarrojo para medición rápida y sin contacto",
    prescription: false,
    features: "Medición en 1 segundo, memoria 32 lecturas",
    accuracy: "±0.2°C precisión",
  },
  {
    id: 7,
    name: "Multivitamínico Completo (90 cápsulas)",
    category: "wellness",
    provider: "Wellness Store",
    price: 24.99,
    priceVES: 899.64,
    discount: 20,
    stock: 45,
    rating: 4.5,
    deliveryTime: "2-4 días",
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    insuranceCompatible: false,
    isNew: true,
    availableFor: ["b2c"],
    description: "Complejo multivitamínico para nutrición diaria",
    prescription: false,
    dosage: "1 cápsula diaria con el desayuno",
    contains: "23 vitaminas y minerales esenciales",
  },
  {
    id: 8,
    name: "Oxímetro de Pulso Digital",
    category: "diagnostics",
    provider: "Laboratorio Nacional",
    price: 28.99,
    priceVES: 1043.64,
    discount: 15,
    stock: 34,
    rating: 4.7,
    deliveryTime: "2-3 días",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    insuranceCompatible: true,
    isNew: false,
    availableFor: ["b2c", "b2b"],
    description:
      "Medidor de saturación de oxígeno y frecuencia cardíaca portátil",
    prescription: false,
    features: "Display OLED, apagado automático",
    accuracy: "SpO2: ±2%, Pulso: ±2bpm",
  },
];

// ------------------------------------------------------
// B2B: Vendors / Proveedores
// ------------------------------------------------------
const B2B_VENDORS = [
  {
    id: "vendor-medisupply",
    name: "MediSupply Profesional",
    rating: 4.8,
    location: "Caracas, Venezuela",
    leadTimeDays: 3,
    terms: "NET 30",
    certifications: ["ISO 13485", "FDA Registered"],
    specialties: ["Suministros médicos", "Consumibles"],
    contactEmail: "ventas@medisupply.com.ve",
    contactPhone: "+58 212-555-0100",
  },
  {
    id: "vendor-tecnomed",
    name: "TecnoMed Equipment",
    rating: 4.9,
    location: "Valencia, Venezuela",
    leadTimeDays: 7,
    terms: "NET 15",
    certifications: ["CE Medical", "FDA Clase II"],
    specialties: ["Equipos médicos", "Tecnología diagnóstica"],
    contactEmail: "info@tecnomed.com.ve",
    contactPhone: "+58 241-555-0200",
  },
  {
    id: "vendor-protecmed",
    name: "ProtecMed Industrial",
    rating: 4.7,
    location: "Maracaibo, Venezuela",
    leadTimeDays: 5,
    terms: "NET 45",
    certifications: ["NIOSH", "ISO 9001"],
    specialties: ["Protección personal", "Suministros industriales"],
    contactEmail: "comercial@protecmed.com.ve",
    contactPhone: "+58 261-555-0300",
  },
  {
    id: "vendor-labplus",
    name: "LabPlus Diagnostics",
    rating: 4.6,
    location: "Barquisimeto, Venezuela",
    leadTimeDays: 6,
    terms: "NET 30",
    certifications: ["ISO 13485", "IVD CE"],
    specialties: ["Laboratorio clínico", "Reactivos IVD"],
    contactEmail: "ventas@labplus.com.ve",
    contactPhone: "+58 251-555-0400",
  },
  {
    id: "vendor-hospcare",
    name: "HospCare Solutions",
    rating: 4.5,
    location: "Caracas, Venezuela",
    leadTimeDays: 10,
    terms: "NET 30",
    certifications: ["ISO 9001"],
    specialties: ["Mobiliario hospitalario", "Logística"],
    contactEmail: "contacto@hospcare.com.ve",
    contactPhone: "+58 212-555-0500",
  },
];

// ------------------------------------------------------
// B2B: productos por segmentos (fake backend)
// ------------------------------------------------------
const B2B_PRODUCTS = [
  {
    id: 101,
    sku: "SYR-5ML-LL-100",
    name: "Jeringas Desechables 5ml Luer Lock (Caja 100 unidades)",
    segment: "consumables",
    segmentLabel: "Material médico fungible",
    family: "Inyección y acceso vascular",
    category: "supplies",
    subcategory: "Jeringas",
    vendorId: "vendor-medisupply",
    vendor: "MediSupply Profesional",
    stock: 500,
    rating: 4.8,
    leadTimeDays: 3,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400",
    availableFor: ["b2b"],
    description:
      "Jeringas estériles para uso profesional, con punta Luer Lock. Uso hospitalario y ambulatorio.",
    certification: "ISO 13485",
    priceTiers: [
      { min: 1, max: 9, priceUSD: 45.0 },
      { min: 10, max: 49, priceUSD: 42.0 },
      { min: 50, max: 999, priceUSD: 38.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 102,
    sku: "GLV-NIT-M-200",
    name: "Guantes Nitrilo Azules Talla M (Caja 200 pares)",
    segment: "consumables",
    segmentLabel: "Material médico fungible",
    family: "Control de infecciones y EPP",
    category: "supplies",
    subcategory: "Guantes de examen",
    vendorId: "vendor-medisupply",
    vendor: "MediSupply Profesional",
    stock: 250,
    rating: 4.9,
    leadTimeDays: 2,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400",
    availableFor: ["b2b"],
    description:
      "Guantes de nitrilo sin polvo, alta resistencia, para procedimientos de enfermería.",
    certification: "FDA Aprobado",
    priceTiers: [
      { min: 1, max: 4, priceUSD: 35.0 },
      { min: 5, max: 19, priceUSD: 32.0 },
      { min: 20, max: 999, priceUSD: 29.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 103,
    sku: "MSK-N95-50",
    name: "Mascarillas N95 Profesionales (Caja 50 unidades)",
    segment: "consumables",
    segmentLabel: "Material médico fungible",
    family: "Control de infecciones y EPP",
    category: "supplies",
    subcategory: "Mascarillas N95",
    vendorId: "vendor-protecmed",
    vendor: "ProtecMed Industrial",
    stock: 800,
    rating: 4.8,
    leadTimeDays: 3,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400",
    availableFor: ["b2b"],
    description:
      "Mascarillas certificadas NIOSH N95 para personal médico en áreas críticas.",
    certification: "NIOSH N95",
    priceTiers: [
      { min: 1, max: 9, priceUSD: 85.0 },
      { min: 10, max: 49, priceUSD: 78.0 },
      { min: 50, max: 999, priceUSD: 72.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 104,
    sku: "SUT-VIC-3-0-12",
    name: "Suturas Absorbibles Vicryl 3-0 (Caja 12 unidades)",
    segment: "consumables",
    segmentLabel: "Material médico fungible",
    family: "Material de quirófano y cirugía",
    category: "supplies",
    subcategory: "Suturas absorbibles",
    vendorId: "vendor-protecmed",
    vendor: "ProtecMed Industrial",
    stock: 120,
    rating: 4.9,
    leadTimeDays: 5,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400",
    availableFor: ["b2b"],
    description:
      "Suturas absorbibles de ácido poliglicólico para cierre de tejidos blandos.",
    certification: "ISO 13485",
    priceTiers: [
      { min: 1, max: 4, priceUSD: 125.0 },
      { min: 5, max: 19, priceUSD: 115.0 },
      { min: 20, max: 999, priceUSD: 105.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 201,
    sku: "MON-MULTI-ICU",
    name: "Monitor de Signos Vitales Multiparamétrico UCI",
    segment: "equipment",
    segmentLabel: "Equipos médicos",
    family: "Signos vitales",
    category: "equipment",
    subcategory: "Monitores",
    vendorId: "vendor-tecnomed",
    vendor: "TecnoMed Equipment",
    stock: 15,
    rating: 4.9,
    leadTimeDays: 14,
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    availableFor: ["b2b"],
    description:
      "Monitor multiparamétrico para UCI y quirófano con ECG, SpO2, NIBP y temperatura.",
    certification: "FDA Clase II",
    priceTiers: [
      { min: 1, max: 2, priceUSD: 2500.0 },
      { min: 3, max: 5, priceUSD: 2350.0 },
      { min: 6, max: 999, priceUSD: 2200.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 202,
    sku: "ECG-12CH",
    name: "Electrocardiógrafo de 12 canales",
    segment: "equipment",
    segmentLabel: "Equipos médicos",
    family: "Cardiología",
    category: "equipment",
    subcategory: "Electrocardiógrafos",
    vendorId: "vendor-tecnomed",
    vendor: "TecnoMed Equipment",
    stock: 20,
    rating: 4.7,
    leadTimeDays: 10,
    image: "https://images.unsplash.com/photo-1584432810601-6c7f27d2362b?w=400",
    availableFor: ["b2b"],
    description:
      "Equipo ECG de 12 canales con pantalla a color y exportación digital de reportes.",
    certification: "CE Medical",
    priceTiers: [
      { min: 1, max: 2, priceUSD: 3800.0 },
      { min: 3, max: 9, priceUSD: 3600.0 },
      { min: 10, max: 999, priceUSD: 3450.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 301,
    sku: "CEFTRIAX-1G-IV-50",
    name: "Ceftriaxona 1g IV (Caja 50 viales)",
    segment: "pharma",
    segmentLabel: "Productos farmacéuticos",
    family: "Antiinfecciosos",
    category: "medications",
    subcategory: "Antibióticos betalactámicos",
    vendorId: "vendor-medisupply",
    vendor: "MediSupply Profesional",
    stock: 90,
    rating: 4.8,
    leadTimeDays: 4,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    availableFor: ["b2b"],
    description:
      "Antibiótico cefalosporina de tercera generación para uso hospitalario intravenoso.",
    certification: "GMP",
    priceTiers: [
      { min: 1, max: 4, priceUSD: 220.0 },
      { min: 5, max: 19, priceUSD: 205.0 },
      { min: 20, max: 999, priceUSD: 190.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 302,
    sku: "MORPH-AMP-10MG",
    name: "Morfina 10mg/1ml (Caja 10 ampollas)",
    segment: "pharma",
    segmentLabel: "Productos farmacéuticos",
    family: "Analgesia y anestesia",
    category: "medications",
    subcategory: "Opioides",
    vendorId: "vendor-medisupply",
    vendor: "MediSupply Profesional",
    stock: 40,
    rating: 4.7,
    leadTimeDays: 5,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    availableFor: ["b2b"],
    description:
      "Analgésico opioide para manejo de dolor severo en entorno hospitalario.",
    certification: "GMP",
    priceTiers: [
      { min: 1, max: 4, priceUSD: 150.0 },
      { min: 5, max: 19, priceUSD: 140.0 },
      { min: 20, max: 999, priceUSD: 130.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 401,
    sku: "TUBO-EDTA-LILA-100",
    name: "Tubo al Vacío EDTA Tapa Lila (Caja 100 unidades)",
    segment: "lab",
    segmentLabel: "Laboratorio y diagnóstico in vitro",
    family: "Toma de muestra",
    category: "diagnostics",
    subcategory: "Toma de muestra",
    vendorId: "vendor-labplus",
    vendor: "LabPlus Diagnostics",
    stock: 300,
    rating: 4.6,
    leadTimeDays: 6,
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    availableFor: ["b2b"],
    description:
      "Tubo al vacío con EDTA para hemogramas y estudios de hematología.",
    certification: "IVD CE",
    priceTiers: [
      { min: 1, max: 9, priceUSD: 55.0 },
      { min: 10, max: 49, priceUSD: 50.0 },
      { min: 50, max: 999, priceUSD: 46.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 402,
    sku: "GLUCO-STRIPS-100",
    name: "Tiras Reactivas de Glucosa (Caja 100)",
    segment: "lab",
    segmentLabel: "Laboratorio y diagnóstico in vitro",
    family: "Point of Care",
    category: "diagnostics",
    subcategory: "Pruebas rápidas",
    vendorId: "vendor-labplus",
    vendor: "LabPlus Diagnostics",
    stock: 180,
    rating: 4.7,
    leadTimeDays: 5,
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    availableFor: ["b2b"],
    description:
      "Tiras reactivas para medición de glucosa capilar en punto de atención.",
    certification: "IVD CE",
    priceTiers: [
      { min: 1, max: 4, priceUSD: 70.0 },
      { min: 5, max: 19, priceUSD: 65.0 },
      { min: 20, max: 999, priceUSD: 60.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 501,
    sku: "BED-ELEC-3FUNC",
    name: "Cama Hospitalaria Eléctrica 3 Funciones",
    segment: "furniture",
    segmentLabel: "Mobiliario y logística hospitalaria",
    family: "Camas y camillas",
    category: "furniture",
    subcategory: "Camas hospitalarias",
    vendorId: "vendor-hospcare",
    vendor: "HospCare Solutions",
    stock: 25,
    rating: 4.5,
    leadTimeDays: 20,
    image: "https://images.unsplash.com/photo-1584466977773-e625c37cdd50?w=400",
    availableFor: ["b2b"],
    description:
      "Cama eléctrica con posiciones Trendelenburg/Fowler, barandas y ruedas con freno.",
    certification: "ISO 9001",
    priceTiers: [
      { min: 1, max: 2, priceUSD: 1800.0 },
      { min: 3, max: 9, priceUSD: 1700.0 },
      { min: 10, max: 999, priceUSD: 1600.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
  {
    id: 502,
    sku: "CART-EMERG-RED",
    name: "Carro de Paro Completo (Carro Rojo)",
    segment: "furniture",
    segmentLabel: "Mobiliario y logística hospitalaria",
    family: "Carros hospitalarios",
    category: "furniture",
    subcategory: "Carros de emergencia",
    vendorId: "vendor-hospcare",
    vendor: "HospCare Solutions",
    stock: 30,
    rating: 4.6,
    leadTimeDays: 15,
    image: "https://images.unsplash.com/photo-1584466977773-e625c37cdd50?w=400",
    availableFor: ["b2b"],
    description:
      "Carro de paro con cajones para medicación, soporte para desfibrilador y cilindro de oxígeno.",
    certification: "ISO 9001",
    priceTiers: [
      { min: 1, max: 2, priceUSD: 1450.0 },
      { min: 3, max: 9, priceUSD: 1380.0 },
      { min: 10, max: 999, priceUSD: 1300.0 },
    ],
    minOrderQuantity: 1,
    taxIncluded: false,
  },
];

// ------------------------------------------------------
// Helpers públicos
// ------------------------------------------------------
export function getMarketplaceProducts(mode = "b2c") {
  return mode === "b2b" ? B2B_PRODUCTS : B2C_PRODUCTS;
}

export function getMarketplaceVendors(mode = "b2b") {
  return mode === "b2b" ? B2B_VENDORS : [];
}
